#!/bin/sh

export PATH=$PATH:/usr/local/bin

cd /web/gtk/USED_CVS_HEAD/gtk+/docs/faq
cvs update 

#cp /web/gtk/USED_CVS_HEAD/gtk+/docs/faq/*.jpg /web/gtk/faq/

rm -f /web/gtk/faq/gtk-faq.sgml
cp gtk-faq.sgml /web/gtk/faq/

cd /web/gtk/faq
#db2html gtk-faq.sgml
rm -f index.html.new
jade -t sgml -ihtml -d ./gdp-gtkfaq.dsl\#html -V nochunks gtk-faq.sgml > index.html.new
cp index.html.new index.html
#./online_faq_fix gtk-faq/*.html
./online_faq_fix index.html
chmod 755 index.html
#chmod 755 gtk-faq/*.html
#(cd gtk-faq; tar cvfpB - .) | tar xvfpB -
#rm -rf gtk-faq
