#!/bin/sh

export CVS_PASSFILE=/home/otaylor/gnomeweb-cvspass
export PATH=$PATH:/usr/local/bin

cd /web/gtk/USED_CVS_HEAD/gtk+/docs/faq
cvs update 

#cp /web/gtk/USED_CVS_HEAD/gtk+/docs/faq/*.jpg /web/gtk/faq/

rm -f /web/gtk/faq/gtk-faq.sgml
cp gtk-faq.sgml /web/gtk/faq/

cd /web/gtk/faq
db2html -u gtk-faq.sgml
./online_faq_fix gtk-faq/gtk-faq.html
mv gtk-faq/gtk-faql.html ./index.html
rm -rf gtk-faq
chmod 755 index.html
