#!/bin/sh

export CVS_PASSFILE=/home/otaylor/gnomeweb-cvspass
export PATH=$PATH:/usr/local/bin

cd /home/web/gtk/www.gtk.org/USED_CVS_HEAD/gtk+/docs/faq
cvs update 

#cp /home/web/gtk/www.gtk.org/USED_CVS_HEAD/gtk+/docs/faq/*.jpg /web/gtk/faq/

rm -f /home/web/gtk/www.gtk.org/faq/gtk-faq.sgml
cp gtk-faq.sgml /home/web/gtk/www.gtk.org/faq/

cd /home/web/gtk/www.gtk.org/faq
#db2html gtk-faq.sgml
rm -f index.html.new
openjade -t sgml -ihtml -d ./gdp-gtkfaq.dsl\#html -V nochunks gtk-faq.sgml > index.html.new
cp index.html.new index.html
#./online_faq_fix gtk-faq/*.html
./online_faq_fix index.html
chmod 755 index.html
#chmod 755 gtk-faq/*.html
#(cd gtk-faq; tar cvfpB - .) | tar xvfpB -
#rm -rf gtk-faq
