image: ruby:2.7

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - apt-get update -y
  - apt-get install curl rsync -y
  - nvmversion=$(curl --silent "https://api.github.com/repos/nvm-sh/nvm/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
  - curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/$nvmversion/install.sh" | bash
  - apt-get install build-essential -y
  - source ~/.nvm/nvm.sh
  - nvm install 14.15.1
  - node -v && npm -v
  - chmod +x setup.sh && bash setup.sh

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build --trace -d public
  - find public -type f -regex '.*\.\(html\)$' -exec npm run minify-html {} \;
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    when: always
    paths:
    - _data/api_fetch
    - public
  only:
  - master
