#!/bin/sh

export CVS_PASSFILE=/home/otaylor/gnomeweb-cvspass
export PATH=$PATH:/usr/local/bin

CVSDIR=/home/web/gtk/www.gtk.org/USED_CVS_HEAD/gtk+/docs/tutorial
INSTALLDIR=/home/web/gtk/www.gtk.org/tutorial2.0/

cd $CVSDIR
cvs update 
cp gtk-tut.sgml $INSTALLDIR

cd $INSTALLDIR
db2html gtk-tut.sgml
mkdir gtk-tut/images
cp $CVSDIR/images/*.png gtk-tut/images

# ./online_tut_fix gtk-tut/*.html
chmod 775 gtk-tut/*.html
(cd gtk-tut; tar cvfpB - .) | tar xvfpB -
rm -rf gtk-tut
