#!/bin/sh

export CVS_PASSFILE=/home/otaylor/gnomeweb-cvspass
export PATH=$PATH:/usr/local/bin

cd /home/web/gtk/www.gtk.org/USED_CVS_12/gtk+/docs
cvs update

cp gtk_tut*.gif gtk_tut.sgml /home/web/gtk/www.gtk.org/tutorial1.2/

cd /home/web/gtk/www.gtk.org/tutorial1.2
sgml2html gtk_tut.sgml
# ./online_tut_fix *.html
chmod 0775 *.html

ln -sf gtk_tut.html index.html
